name: Prettier Format

on:
  push:
    branches: [ main, master ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install --save-dev prettier
        
      - name: Run Prettier fix
        run: npx prettier --write .
